export const ADMIN_MESSAGE_PREVIEW_LENGTH = 220;
export const NAVBAR_SCROLL_DELTA_THRESHOLD = 8;
export const NAVBAR_SCROLL_IDLE_SHOW_DELAY_MS = 190;
export const NAVBAR_HIDDEN_TRANSLATE_Y = 108;
export const NAVBAR_HIDDEN_SCALE = 0.985;
export const NAVBAR_HIDDEN_OPACITY = 0.86;
export const AVATAR_PULSE_MIN_OPACITY = 0.92;
export const AVATAR_PULSE_MAX_OPACITY = 1;
